common:
  vars:
    - &vars_group_1
      GROUP_VAR_1: "Group 1 var"
    - &vars_group_2
      GROUP_VAR_2: "Group 2 var"
  cache: &default_cache_paths
    cache_paths:
      - $HOME/.gradle/caches
      - $HOME/Library/Caches/CocoaPods
      - $FLUTTER_ROOT/.pub-cache
  scripts:
    - &echo_script_1
      name: Step 1 name
      script: |
        echo "Running script 1"
        echo "Script Var is:"
        echo $PUBLIC_ENV_VAR
        echo "App Var is:"
        echo $EXTERNAL_VAR
        echo "Group 1 Var is:"
        echo $GROUP_VAR_1
        echo "Group 2 Var is:"
        echo $GROUP_VAR_2
    - &echo_script_2
      name: Step 1 name
      script: |
        echo "Running script 2"
        echo "Script Var is:"
        echo $PUBLIC_ENV_VAR
        echo "App Var is:"
        echo $EXTERNAL_VAR
        echo "Group 1 Var is:"
        echo $GROUP_VAR_1
        echo "Group 2 Var is:"
        echo $GROUP_VAR_2

workflows:
  my-workflow_1:
    name: Test workflow 1
    instance_type: mac_mini
    max_build_duration: 30
    environment:
      groups:
        - group_1
      vars:
        <<: *vars_group_1
        PUBLIC_ENV_VAR: "some public var 1"
    cache: 
      <<: *default_cache_paths
    scripts:
      - *echo_script_1
  my-workflow_2:
    name: Test workflow 2
    instance_type: mac_mini
    max_build_duration: 30
    environment:
      groups:
        - group_1
      vars:
        <<: *vars_group_2
        PUBLIC_ENV_VAR: "some public var 2"
    scripts:
      - *echo_script_2
