workflows:
  my-workflow:
    name: Test workflow
    instance_type: mac_mini
    max_build_duration: 30
    environment:
      groups:
        - group_1
      vars:
        PUBLIC_ENV_VAR: "some public var"
    scripts:
      - name: Step 1 name
        script: |
          echo "Script Var is:"
          echo $PUBLIC_ENV_VAR
          echo "App Var is:"
          echo $EXTERNAL_VAR
    publishing:
      email:
        recipients:
          - vladfar23@gmail.com
