common_templates:
  common_vars:
      &vars_group_1
        GROUP_VAR_1: "Group 1 var"
  scripts:
    - &echo_script
      name: Step 1 name
      script: |
        echo "Script Var is:"
        echo $PUBLIC_ENV_VAR
        echo "App Var is:"
        echo $EXTERNAL_VAR
        echo "Group 1 Var is:"
        echo $GROUP_VAR_1

workflows:
  my-workflow:
    name: Test workflow
    instance_type: mac_mini
    max_build_duration: 30
    environment:
      groups:
        - group_1
      vars:
        <<: *vars_group_1
        PUBLIC_ENV_VAR: "some public var"
    scripts:
      - |
        # Separator
        echo "----------"
      - *echo_script
    publishing:
      email:
        recipients:
          - vladfar23@gmail.com
